name = "afrcloud-siren"
main = "build/worker/shim.mjs"
compatibility_date = "2024-05-23"
minify = true
workers_dev = true


routes = [

  { pattern = "mr44j.grentongers.dpdns.org", custom_domain = true },
  { pattern = "ava.game.naver.com.mr44j.grentongers.dpdns.org", custom_domain = true },
  { pattern = "quiz.int.vidio.com.mr44j.grentongers.dpdns.org", custom_domain = true },
  { pattern = "graph.instagram.com.mr44j.grentongers.dpdns.org", custom_domain = true },
  { pattern = "help.viu.com.mr44j.grentongers.dpdns.org", custom_domain = true },
  { pattern = "support.zoom.us.mr44j.grentongers.dpdns.org", custom_domain = true },
  { pattern = "cache.netflix.com.mr44j.grentongers.dpdns.org", custom_domain = true },
  { pattern = "graph.facebook.com.mr44j.grentongers.dpdns.org", custom_domain = true },
  { pattern = "dogseechew.com.mr44j.grentongers.dpdns.org", custom_domain = true },
]

[[kv_namespaces]]
binding = "SIREN"
id = "2197f26993c3401ab552eae1dbc7b07c"

[build]
command = "cargo install -q worker-build && worker-build --release"

[env.dev]
build = { command = "cargo install -q worker-build && worker-build --dev" }

[vars]
UUID = "bbbbbbbb-cccc-4ddd-eeee-ffffffffffff"
MAIN_PAGE_URL = "https://raw.githubusercontent.com/AFRcloud/AFR-Cloud/refs/heads/master/web/index.html"
SUB_PAGE_URL = "https://raw.githubusercontent.com/AFRcloud/AFR-Cloud/refs/heads/master/web/sub.html"
LINK_PAGE_URL = "https://raw.githubusercontent.com/AFRcloud/AFR-Cloud/refs/heads/master/web/link.html"
CONVERTER_PAGE_URL = "https://raw.githubusercontent.com/AFRcloud/AFR-Cloud/refs/heads/master/web/converter.html"
